### ISSUE TITLE
Hello, World - Intro to HTML

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#1]
# Hello, World.

In your first assignment you will end up with a web page, no matter how simple, published on the web.

## Objectives

* Get to know your text editor.
* Introduce yourself to working on the command line.
* Publish a web page.

## Requirements

* Have `git`, `hub`, and `node` installed. We should have done this together in class.
* All of your HTML (and CSS if you do _adventure_ mode) should be formatted cleanly and consistently
  (use your editor to your advantage).

### Explorer Mode

* [ ] Follow all of the setup instructions (See "Assignment Setup").
* [ ] Compose a short essay (just a couple paragraphs at most) about a hobby you either enjoy, or would like to learn
      about. We will be expanding on this page in future assignments, so pick something fun!
* [ ] Put your short essay into an HTML page, using appropriate semantic HTML tags. Give your webpage a simple header
      and footer as well.
* [ ] Deploy your site.

### Adventure Mode

* [ ] Research the `id` and `class` HTML attributes.
* [ ] Use valid CSS to style the page (in the neighborhood of a couple dozen CSS declarations).
* [ ] Use at least one image somewhere on the page.

### Epic Mode

* [ ] Create a full layout for your page (heading, navigation, sidebar, footer, etc.).
* [ ] Use more complex CSS selectors than we covered in class, e.g. attribute selectors or sibling selectors.

## Additional Resources

* https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags
* http://atozcss.com/start-here/
* http://www.evolutionoftheweb.com

## Reading Material

To prep for tomorrow's lesson, you can [read about CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS).

**Comment by solismc** [comment]
https://github.com/solismc/hello-world

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/830Y70l464P1t7RXfa/200w_d.gif)

**Comment by solismc** [comment]
https://github.com/solismc/hello-world
