### ISSUE TITLE
Week 03 Day 2 - Cloudy with a chance of Syntax Error - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#10]
Using a popular weather API, Create a web site that allows a user to search for a location and gets that places weather.

## Objectives

- Practice working with an API
- Practice working with data that was structure by a third party

## Requirements

- Using `openweathermap.org`, create a simple UI that allows a user to search for the current weather by zip code or city

### Explorer Mode

- [ ] Create a simple HTML page that has a text box and a search `button`
- [ ] Allow the user to type in a place, click the search button, and , using `openweathermap.org`, get the current weather for that location
- [ ] Display the weather to user by adding elements to the DOM.
- [ ] Allow the user to search by zip or city name.

## Adventure Mode

- [ ] Using the HTML5 Geolocation API, search for the users current location when page loads
- [ ] Store the Users last search and pull it and search for the value on page load
- [ ] remove the need for teh search button and search when the user stops typeing. HINT: use setTimeout and the change event. to track when the user stops typing.

## Epic Mode

- [ ] Add a type a head using Google Places API
- [ ] Head back to blackjack and use [https://deckofcardsapi.com/](https://deckofcardsapi.com/) as your API

**Comment by solismc** [comment]
https://github.com/solismc/weather-api

Mark, the button is working and displays temp. I read the documentation and I found the path and variable names that I need to call to display them on the screen. I'll be adding that later today. I'm also going to fix the temp to display in F, not K.

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/1lyR0oO988RNoHafRK/200w_d.gif)
