### ISSUE TITLE
Week 03 Day 4 - Hack Day & Tic Tac Toe - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#12]
---
title: Designing Tic-Tac-Toe
draft: true
---

With a partner, create a design for a tic-tac-toe game. Do _not_ worry about writing code; rather, practice your technical design skills (i.e. thinking about _how_ you would code this).

## Objectives

- Plan and design "ideas"
- Collaborate and communicate effectively around technical ideas

## Requirements

Features to consider:

- [ ] Game should be played on the same computer.
- [ ] As a user, I should be able to see a tic-tac-toe board.
- [ ] As a user, the game should alternate turns, between `X` and `O`.
- [ ] As a user, I should be able to click in a square and play either `X` or `O`, respective of the turn.
- [ ] As a user, when I get three in a row, I should be told I've won and the game should be over.

**TIPS:**

- These designs should be so detailed that you could give them another team and they could implement it with few (if any) questions.
- If at any time you want to validate a piece of your design (e.g. the algorithm, event handling, or UI/UX), you can create an _extremely simple_ site that proves or disproves your idea.

### Explorer Mode

Submit a full design of how to approach this problem. This should include:

- [ ] A digital mock up (created using software, or a photo/scan of an analog drawing)
- [ ] Implementation details, such as how you are implementing each square
- [ ] A list of events you are listening for
- [ ] _psuedo-code_ describing your program (e.g. event-handling, game logic)

### Adventure Mode

- [ ] Plan the implementation of a "vs computer" mode, that picks a random square.

_or_

- [ ] Take a swing at creating your tic-tac-toe game.
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable.

### Epic Mode

- [ ] Modify your "vs computer" mode to follow a specific strategy (of your choice).

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups and prototypes.
- Read about [Pseudocode](https://en.wikipedia.org/wiki/Pseudocode)

**Comment by solismc** [comment]
## Tic Tac Toe



#### Requirements:


- [ ] We need Play Button
  - [ ] Play Button hides after game started
- [ ] We need Restart Button
  - [ ] Restart Button appears when game ends
- [ ] We need the board
  - [ ] Create nine sections each numbered from 0-8
    - [ ] Flex three sections at a time 
    - [ ] Use borders to resemble the board.
- [ ] Players alternate turns
  - [ ] Player 'x' takes his turn
    - [ ] if there is no more space to play, declare tie
    - [ ] Player 'x' picks an empty spot
    - [ ] if there is three in line game ends, declare Player 1 winner
    - [ ] else Player 'o' turn
  - [ ] Player 'o' takes his turn
    - [ ] if there is no more space to play, declare tie
    - [ ] Player 'o' picks an empty spot
    - [ ] if there is three in line game ends, declare Player 2 winner
    - [ ] else Player 'x' turn



#### Optional:


- [ ] Apply rules to decide which player start
- [ ] Keep scores
- [ ] Play best of (3,5...)

![tic-tac-toe mock-up](https://user-images.githubusercontent.com/41206406/44048264-e11a5c70-9efe-11e8-8ba7-1d6a0b902f45.png)

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/4TtsUGA4zUVgqELVrh/200w_d.gif)
