### ISSUE TITLE
Week 05 Day 1 - Recovery Blog - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#17]
The last 4 weeks have been a marathon of training your brain with new ideas and concepts; and just like during a training routine, you need to take some recovery days. Today, you should create a blog post as well go back and revisit an old project and let your brain recovery before we take off again.

## Objectives

- Practice talking about technology
- Reinforce a topic we have covered in class

## Requirements

- Create a blog on [Medium](https://medium.com/).

### Explorer Mode
* [x] You have grown as a developer and a person in the last 4 weeks. Create for me a blog post on medium on 1 of the following prmpts

    - Pick 1 topic technically that we have learned and create a blog post explaining it to a new developer

    - Blog about a struggle that you have encountered and overcome during your tenure here so far.

    - Pick a new techonlogy that we haven't hit yet (or won't) and create a intro blog for that. 

* [x] Submit the link to your published blog post when turning in this assignment.

### Adventure Mode

* [ ] Go back and finish up any outstanding work.

* [ ] Go back to a previous assignment and work on it some more. This could trying to tackle a harder level, working on the UI/UX, refactoring the code to a new idea that we covered (e.g. functions and abstractions), or adding unit tests.

* [ ] To turn this in, link to the other project's repository, and describe what you did.

### Epic Mode

* [ ] Using the built in react testing [framework](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests). Create unit tests for a past project. This will be a bit challenging because we have not covered TDD much in class, but take a swing at this.

**Comment by solismc** [comment]
https://medium.com/@manolocsolis/hack-a-thons-thoughts-and-lessons-learned-bebc0887cf8f

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/5hs4g333no45pTNEyZ/200w_d.gif)
