### ISSUE TITLE
Week 05 Day 2 - Function Junction - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#18]
## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of types, functions, argument-handling, loops, and conditional statements

## Requirements

1.  Fork [this repository](https://github.com/suncoast/function-junction) to your own account.
2.  Change into your training directory
3.  Clone your repository: `hub clone function-junction`
4.  Change into your project's directory: `cd function-junction`
5.  Install the dependencies: `yarn install` (or just `yarn` for short)
6.  Open in Code: `code .`
7.  Start the test runner: `yarn test`
8.  Open `src/functions.test.js` and work on functions until tests pass.
9.  Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

### Explorer Mode

- [x] All tests passing
- [x] No linter warnings
- [x] Turn in the homework using the URL to your repository on Github.

### Adventure Mode

- [ ] If you used "built-in" JavaScript methods like `String.reverse()` or `Array.max()` to solve these problems, try implementing them from scratch.
- [ ] Vice-versa: if you implemented your solutions from scratch, look in the documentation linked below to see if JavaScript has any built-in functions to help solve these problems.

### Epic Mode

- [ ] Expand the `sum` and `max` functions to take arrays instead of numbers and update the tests so they pass.
- [ ] Create your own simple functions with tests.
- [ ] Anytime in your code that you used a `for` loop or a `while` loop, convert it to use a `map`, `filter` or `reduce`.

## Additional Resources

Reference the documentation on MDN to find what kind of helpful functions might already be on `Array` and `String` in JavaScript.

- [String Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String).
- [Array Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).

**Comment by solismc** [comment]
Mark,

I have finished the functions. I forked this repo. It shows. I am getting some errors when I commit. I have it saved locally but can't push to the Git repo which is set up. I keep getting some errors.

**Comment by solismc** [comment]
https://github.com/solismc/function-junction

**Comment by mdewey** [comment]
Find me to get this git issue resolved

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/1wXeZpHD5jYVqhilyY/200w_d.gif)
