### ISSUE TITLE
Style Your World - intro to css

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#2]
# Expanding Your World.

In this assignment you will end up with a simple styled web page, published on the web.

## Objectives

* Practice using your tools text editor.
* Explore new CSS properties 
* Publish a web page.

## Requirements

* Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

* [ ] Follow all of the setup instructions (See "Assignment Setup").
* [ ] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look at "bad" as you want. Here are some sites to gain inspiration. [https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
* [ ] Add a second page about your hobby with (atleast) 2 pictures and with other facts about your hobby. 
* [ ] Add a menu to the your site so a user can go back and forth between the new pages. 
* [ ] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your pages. 
* [ ] Deploy your site.

### Adventure Mode

* [ ] use pseudo-classes to style elements when you hover the mouse over them 
* [ ] Add a third page, that has a table, with a few a few rows & columns. Create this table to have alternating colored rows, and a hover over color. 
* [ ] Make a nav bar that sticks to the top of the page (see the nav bar here for example: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
* [ ] Make a footer that always sticks to the bottom of the page

### Epic Mode

* [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animated all elements on your page to some extent

## Additional Resources

CSS
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS

HTML
* https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags
*https://css-tricks.com/snippets/css/a-guide-to-flexbox/

## Reading Material

To prep for tomorrow's lesson, you can read about media queries. 
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by solismc** [comment]
http://hello-world.manuelsolis.surge.sh

Mark, I fixed the issue with the header image not displaying correctly.

**Comment by mdewey** [comment]
Remember I need you to submit your github repository here, so I can look at your code.

**Comment by solismc** [comment]
https://github.com/solismc/hello-world

Sorry about the confusion, Mark. Here it is...

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/l3q2DbzOZjFYNflII/200w_d.gif)
