### ISSUE TITLE
Week 06 Day 2 - Snowman, the Resurgence  - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#22]
---
title: It doesn't have to be a snowman?
draft: true
---

Yesterday, you started to built the game _Snowman_

## Objectives

* Reinforce component architecture in React
* Effective use props and state in React
* Practice refactoring and CSS
* Work with an existing code base

## Requirements

- Continue to work on and improve an existing project

### Explorer Mode

* [ ] Complete explorer, adventure mode, and epic mode from last night's Snowman

### Adventure Mode

* [ ] Expand your word to include words of varying lengths and to have words with multiple letters (You can use this as inspiration [Expanded word list](https://raw.githubusercontent.com/atebits/Words/master/Words/en.txt))

### Epic Mode

* [ ] Create different word lists and let the user choose the theme. Example, create a word list that is only animals, and have only the words come from that list.

**Comment by solismc** [comment]
https://github.com/solismc/snowman

Still need to work on building the images as the letters are guessed.

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/1NZ3y92OSvXDyTjH2M/200w_d.gif)
