### ISSUE TITLE
Week 06 Day 3 - Pet Adoption  - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#23]
For this project, you will forking an existing repo and adding ore functionality to it. You will completing the UI as well as adding a "save for later" feature. 

## Objectives

* Work with creating components
* Work with a Github workflow
* Work with local storage

## Requirements

First you need ot fork this repo [https://github.com/mdewey/puppy-adoption](https://github.com/mdewey/puppy-adoption). 

Then you will need to clone your fork to your local machine. You will be doing all of your development on that fork. 

### Explorer Mode

* [ ] Add some styling to the page. Make the header look like a header, add styling to the nav bar, and style the pets using flexbox to wrap around the page. 
* [ ] Make a `Pet` component to have all logic, HTML and styling for a pet. 
* [ ] Hook up the `Save for later! Arf!` to save the current pet to local storage. 
* [ ] On the main page, display the number of pets save to local storage
* [ ] Submit a pull request back to [https://github.com/mdewey/puppy-adoption](https://github.com/mdewey/puppy-adoption)

### Adventure Mode

* [ ] Add React Router and create the follow pages: 
    - [ ] Index page to view all pets
    - [ ] a page to view my saved pets
    - [ ] a page to view all the details about a pet
* [ ] Add more information to each Pet on the index page. 

*NOTE*: Remember to think in components

### Epic Mode

* [ ] Add search filters and a easier UI to discover pets for their family

**Comment by solismc** [comment]
OK, I am really excited and proud of this one! I need to fix the images but it works on desktop, iPad, and iPad Pro. 

https://github.com/solismc/puppy-adoption

I'm still going to work on the links to the 2 pages

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/2A4zwCmLSbpIRUFAvN/200w_d.gif)

**Comment by mdewey** [comment]
Good work on the CSS, but you are missing the localStorage aspect and the refactor to use a component.

**Comment by solismc** [comment]
https://github.com/solismc/puppy-adoption
