### ISSUE TITLE
Week 07 Day 2  - Let's go to the Vue-vies - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#26]
Using a the movie APIs, you will be creating a sample project to continue working with Vue.js

## Objectives

- Practice working with an API
- Practice working with data that was structure by a third party

## Requirements

- Use this API [https://developers.themoviedb.org/3/getting-started/introduction](https://developers.themoviedb.org/3/getting-started/introduction)
    - You will have to create an account to get a key, Feel free to use the address and phone number of campus to sign up with
- Create a simple UI that allows for Users to search for a movie
- You will be using this endpoint = [https://developers.themoviedb.org/3/search/search-movies](https://developers.themoviedb.org/3/search/search-movies)

### Explorer Mode

- [ ] Create a page that has a textbox that allows the user to type in a search term.
- [ ] Using the endpoint above, pass the endpoint what the user typed in and display the results,
- [ ] Style your page to make your website look like a modern site.
- [ ] Add a Section to your page that shows the user the trending movies. Use this endpoint: [https://developers.themoviedb.org/3/trending/get-trending](https://developers.themoviedb.org/3/trending/get-trending)

### Adventure Mode

- [ ] Allow the user to save movies to local storage to look at later
- [ ] Allow the user to search both TV shows and Movies
- [ ] Using Vue-Router, set up the site to handle so a use can see more data about a movie or tv show
- [ ] Explore the API and use any endpoints you find interesting

**Comment by solismc** [comment]
I added the fetch function. In the process, I broke the button. Need to fix that.

https://github.com/solismc/vue-movie-search

**Comment by mdewey** [comment]
This is incomplete in the current commit  on github. 

I am looking for: 
- To use the component that you have created
- to show a list of movies from the API
