### ISSUE TITLE
Final Project 1 - It starts with a plan. - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#27]
We are starting the final stretch of the cohort. This means we are starting to focus on our final projects. 

When we go to start a new project. The first step is create an elevator pitch. This is a short description that describes what your final project is doing. This should be simliar to what you said last week for lab.

The second step is to always plan out what we are doing. These early plans often take the shape of wire frames. This means that our first task for the capstone projects is create our wire frames.

The elevator pitch wire frames should be treated as a detailed road map. When these are created, these should be treated as law; it can be changed, but must be changed with purpose.

## Objectives

* Finalize the idea for your capstone
* Create wire frames for your capstone project

## Requirements

* Using your favorite way to create wire frames (paper, whiteboard, website), create all the pages for your site no matter how simple the pages are. 
* Create a new repository for your capstone project

### Explorer Mode, Due Friday 9/7

* [ ] Create the elevator pitch for your final projects. 
* [ ] Place this in the `README.md` of your capstone project repository 

### Explorer Mode, Due Monday 9/10
* [ ] Create a wire frame for each page in your page you capstone. 
* [ ] Place these wire frames in an `.idea` folder of your capstone project repository.

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups and prototypes.

**Comment by solismc** [comment]
https://drive.google.com/drive/folders/1JhyQwtYZS1Iv8lkxLAJ31G1gWQBAb_0N?usp=sharing

Mark, I saved a PDF of my wireframes in a Google Drive folder. The link above should give you access to it.

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/65MqgeebpNtUumtQ4U/200w_d.gif)
