### ISSUE TITLE
Week 07 Day 3 - Double Back - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#28]
Over the past couple of weeks we have been learning React and did a variety of projects; and over the last week we have learned a new framework, Vue.js. For this project, go back to a selected project that we did in React and recreate it using Vue.js.

## Requirements

* Recreate a React App in Vue

### Explorer Mode

- [ ] Recreate `Color Picker`. 

### Adventure Mode
- [ ] Recreate `Snowman` 

### Epic Mode
- [ ] Recreate `Minesweeper`
 

 *NOTE* Remember that you should also be working on your capstone project this weekend as well.

**Comment by solismc** [comment]
https://github.com/solismc/Assignments/issues/28

**Comment by mdewey** [comment]
This is not done, this shouldn't be closed

**Comment by solismc** [comment]
https://github.com/solismc/vue-color-picker

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/1QddXIbRZKdu5YluFR/200w_d.gif)
