### ISSUE TITLE
Week 08  Day 1 - A Whole New World - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#29]
Today you learned a new language and will be starting to explore it more in depth in the coming weeks. Like any good craftsman, the first thing you need is to learn your tools. Tonight, you will be setting up your developer environment, creating a simple console application, and writing a short blog. 

## Objectives

* Set up your dev machines
* Create a simple console application to ensure your machine is set up correctly
* Write a blog article to practice talking about technology 

### .NET Students 

 - Install the .NET Core SDK here: [https://www.microsoft.com/net/download](https://www.microsoft.com/net/download)
- Install the `C#` plugin in VS Code. 

- To verify everything was installed correctly, run `dotnet -v` in your terminal.

### Ruby

You should already have Ruby installed. 

#### Simple Console Application 
* [ ] Create a console application that guesses a number that a user has thought of ,between 1 and 100. This will use a [`binary search`](https://www.programmerinterview.com/index.php/puzzles/minimum-guesses-1-100/) to guess the correct number 
* [ ] Here is the JavaScript, in browser, algorithm to follow. Make sure to understand this first before writing new code: [`https://codepen.io/ambethia/pen/KNewBb`](https://codepen.io/ambethia/pen/KNewBb). 
**NOTE** You will be translating this from the event driven paradigm of HTML to the more procedural paradigm of a console application. 
* [ ] For Explorer Mode, you do not have to put in menu or other user experience "nice to haves", focus on the just the core algorithm.

#### Blog 
* [ ] We have tackled front end development and are about to tackle a new language. You have grown as a developer and a person in the last 7 weeks. Create for me a blog post on medium on 1 of the following prompts

- Pick 1 topic technically that we have learned and create a blog post explaining it to a non-technical person.

- Blog about a struggle that you have encountered and overcome during your tenure here so far.

- Pick a new technology that we haven't hit yet (or won't) and create a intro blog for that.

### Adventure Mode

* [ ] Create a nice user experience. Include features such as 
`Try again` and `Welcome, press enter to start`

### Epic Mode

* [ ] Eventually we will be using a MVC application structure. To prepare for this, refactor your code to have all your business logic in separate class and all your console interaction in the main class. 

## Additional Resources

* Ruby Resouces: 
    - [https://learnrubythehardway.org/book/ex33.html](https://learnrubythehardway.org/book/ex33.html)

* .NET
    - [https://docs.microsoft.com/en-us/dotnet/](https://docs.microsoft.com/en-us/dotnet/)

**Comment by solismc** [comment]
https://medium.com/@manolocsolis/computer-languages-different-paths-same-result-9119e1cd10a

**Comment by solismc** [comment]
https://medium.com/@manolocsolis/computer-languages-different-paths-same-result-9119e1cd10a

Hi Mark,

Here is the link to my blog. I shared with you my thought process on the number guesser earlier. I'm going to work on the coding of the variables and if-else statements and put it into a .cs file. I'm closing it for now so you can see my progress. I'll re-open to update once I have the CS file.

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/1gdkCL3eKStMIwKEzu/200w_d.gif)
