### ISSUE TITLE
Week 01 day 3 - Octodex - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#3]
# Octodex

GitHub has a great mascot called OctoCat. OctoCat even has it's own gallery of variations, created by GitHub itself and fans, called [Octodex](https://octodex.github.com).

Unfortunately, the Octodex is not responsive*! Today, your task is to recreate the layout of The Octodex as closely as possible, but make it responsive. You can use all the tools you have at your disposal to get the job done. Use your browser's Developer Tools to inspect their site to find the exact font sizes and padding amounts.

\* Well, _actually_ it uses javascript set the number of columns on page load, but we want to see interactive responsiveness when we resize our window!

## Objectives

- Build on your knowledge of HTML & CSS
- Implement a responsive design with media queries
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.
- Use flexbox techniques layout pages.

## Requirements

- You should strive to implement the design as close as possible, though, especially if you've never touch HTML or CSS before, this can be extraordinarily difficult, and will take a lot of practice and mileage.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

* [ ] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors. Download some of your favorite 
* [ ] Octocat images to use in your page (12-16 or so). Your layout should be flexible, but doesn't need to _perfectly_ responsive. 
* [ ] Use flexbox styles to layout the header and the Octocats (hint: checkout the `flex-wrap` property).

## Adventure Mode

* [ ] If you're feeling adventurous, use CSS _media queries_ to resize the Octocat containers to look great as a single full-width column on small screens, and a nice grid on bigger screens.
* [ ] watch this video to work more with media queries https://www.youtube.com/watch?v=2KL-z9A56SQ

## Epic Mode
* [ ] Go back to your hobby website and update the site to be mobile friendly and responsive. 

## Additional Resources

* https://css-tricks.com/snippets/css/a-guide-to-flexbox/
* http://www.evolutionoftheweb.com

## Recommended Practice: 

Even if you have completed them, repetition helps enforce concepts

* https://flexboxfroggy.com/
* https://mastery.games/p/flexbox-zombies

## Reading Material

To prep for tomorrow's lesson, you can [read about CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS).

**Comment by solismc** [comment]
https://github.com/solismc/octodex

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/paMqU8U8XPd9KIa5oH/200w_d.gif)
