### ISSUE TITLE
Week 08  Day 2 - Wax on, Wax Off - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#30]
>A **koan** is a riddle or puzzle that Zen Buddhists use during meditation to help them unravel greater truths about the world and about themselves. Zen masters have been testing their students with these stories, questions, or phrases for centuries.

As we learn a new language, we need to practice the new ideas, syntax and paradigms that come what that language. The idea of language Koans helps both beginners and veterans learn the ins and outs of language. 

## Objectives

* Complete your language Koans

### .NET Students

- Head here: [https://github.com/suncoast-devs/DotNetCoreKoans](https://github.com/suncoast-devs/DotNetCoreKoans) and follow the directions in the README.md. This will have you fork this repository, clone it and practice the 

### Ruby Students

- Head here: [http://rubykoans.com/](http://rubykoans.com/) and follow the directions

### Explorer Mode

* [ ] Complete the Koans

### Adventure Mode

* [ ] (.NET) There are a few Koans that were commented out, comment these in and complete them. 

### .NET Students

- Here are some videos about inheritance and interfaces to help gain some more exposure.
    - Interfaces: https://www.youtube.com/watch?v=neTerkT7LhE
    - Inheritance: https://www.youtube.com/watch?v=m0DJIhmUtP8
    - Getters & Setters: https://www.youtube.com/watch?v=M0IY3712QCE

**Comment by solismc** [comment]
https://github.com/solismc/DotNetCoreKoans/tree/master/Koans

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/1poYlvX7SI3OrBBpxZ/200w_d.gif)
