### ISSUE TITLE
Final Project 2 - Lets get Visual - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#32]
With the wire frames created, we need to start breathing life into our application. The next step would be to create the HTML & CSS. This is the next step because, remember, it all comes down to HTML. This is what the user sees. Do not worry about making the site dynamic or breaking into components. 

## Objectives

* Create the HTML and CSS for the final project

## Requirements

* Using `app-app`, `create-react-app` or `vue create` to start implementing your HTML

### Explorer Mode, Due Wednesday 9/19

* [ ] Create the HTML and CSS version of your wireframes. Stay as true as possible.

**Comment by solismc** [comment]
https://github.com/solismc/personality-test

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media1.giphy.com/media/vG24BtU6r5n9K/200w_d.gif)
