### ISSUE TITLE
Final Project 3 - Take the next steps - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#35]
With the wireframes, html and css created, next up and will be to continue on breathing life into our projects. After the CSS, HTML, and wireframes, we need to start thinking about breathing life into our apps. Take today to start creating your front end, ERD and API definitions.

## Objectives

* Start making your front end dynamic and creating components
* Create an ERD for your database, at least a first draft
* Start thinking about your API

## Requirements

* A React or Vue App with your HTML and CSS
* a ERD Diagram on paper/whiteboard/image/online builder 

## Explorer Mode
* [ ] Work on your final project, submit your repository here.

**Comment by solismc** [comment]
Mark, here is the progress on my capstone project. I'll slack you an image of my database.

https://github.com/solismc/personality-test

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media3.giphy.com/media/3o7aCXpKkT0hH2zdIY/200w_d.gif)
