### ISSUE TITLE
Week 10 Day 2 - Suncoast Overflow - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#38]
---
title: Suncoast Overflow
draft: true
---

As we explore the concepts of a full stack web app, a good way to practice is to duplicate an existing site. For this project you will be creating a copy of a site that you know very well, StackOverflow.

The finished product will be due Monday, so this will be a little bigger.  Pace yourself, but don't sleep on it. 

First, we need to the database schema, and start build the API for the core functionality

## Objectives

* Create a full stack web app, from Database, to API, to frontend, as well as styled
* Practice working in groups

## Requirements

In groups of 2, create an anonymous question and answer site, that allows users to up-vote and down-vote questions and answers. 

The core functionality is: 
- [ ] as a user I should be able to view and search questions asked
- [ ] As a user I should be able to view a question and its answers
- [ ] As a user I should be able to post a question, this can anonymous, and should be be Explorer Mode
- [ ] As a user I should be able to answer a question
- [ ] As a user I should be able to up/down vote a answer
- [ ] As a user I should be able to up/down vote a question

### Explorer Mode

* [ ] Create a ERD for the core functionality above
* [ ] Create API definitions for the all the endpoints needed. This should include urls, params, body, and return types. 
* [ ] Start building out the API

### Adventure Mode

* [ ] Work on your capstone project

**Comment by solismc** [comment]
https://github.com/dnsomoano/suncoast-overflow

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media3.giphy.com/media/HmEYYrsiMZDJC/200w_d.gif)
