### ISSUE TITLE
Week 02 Day 1 - Scoreboard - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#5]
# Score Board

For this assignment you will creating a simple interactive score board for your favorite sport.

A User should be able to update a score and the teams playing.

### Explorer Mode

Should resemble this:
![markup](https://raw.githubusercontent.com/suncoast-devs/handbook/master/content/curriculum/fundamentals/javascript/assignments/assets/scoreboard-day-1.buttons.PNG)

- [ ] implement the basic HTML
- [ ] implement the basic formating. Do not worry about styling (colors and fonts and the like)
- [ ] add click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard coded" value

### Adventure Mode

- [ ] Complete Explorer Mode
- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport
- [ ] Add some custom CSS to make it more colorful. Have fun with it
- [ ] Make the layout responsive

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately
- [ ] Save/load the information to local storage
- [ ] Add CSS to the winning teams score to indicate who is currently winning
- [ ] add anything else that your sport would have on its score board (fouls, sacks, shots on goal, etc);
- [ ] Improve the UX to help making score keeping by your sport easier

**Comment by solismc** [comment]
https://github.com/solismc/scoreboard

Still needs some more work...

**Comment by mdewey** [comment]
This is incomplete until you finish out the javascript
