### ISSUE TITLE
Week 02 Day 2 - Rock Paper Scissors - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#6]
# Rock-Paper-Scissors

Create a simple Rock-Paper-Scissors game

## Objectives

- Work with JavaScript and the DOM
- Practice if/then logic

### PRO-TIP
Do not worry about CSS for explorer mode, only do as HTML to show the functionality 

### Explorer Mode

- [ ] As a user I should be able to see three buttons for each player
- [ ] as a user, I should be able to pick an option for each player
- [ ] As a user,after each player makes their selection, I should be told who won and the game should be over

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice)
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by solismc** [comment]
https://github.com/solismc/rock-paper

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/1zgNRy9k6zxxZHOxWs/200w_d.gif)
