### ISSUE TITLE
Week 03 Day 1 - Catch your Breath - 

### ISSUE THREAD

**Issue by mdewey** [solismc/Projects#9]
---
title:  Catch your Breath
---

We have been going at a fast pace for the past couple of weeks. Every so often, you need to reflect on how far you have come.

In this assignment, we are going to take a little _code_ break and create a blog post. Writing is a good way to reflect on what you have done and also share some knowledge. The best way to get better at talking about technology is practice. Blog posts are a way to practice that skill.

## Objectives

- Practice talking about technology.
- Reinforce a topic we have covered in class.

## Requirements

- Create a blog on [Medium](https://medium.com/).

### Explorer Mode

- [ ] On [Medium](https://medium.com/), create a blog post that talks about a concept we have went over in class. This could anything topic from HTML, CSS or JavaScript, or a "lesson learned" from the past couple of weeks. As a challenge, consider picking a topic you think you are weak on. Remember, you are creating developer-focused blog post.
- [ ] Submit the link to your published blog post when turning in this assignment.

## Adventure Mode

- [ ] As we progress, we will be using different tools to work our brain. Today, head over to [HackerRank](https://www.hackerrank.com/). This is another tool, like [Codewars](https://www.codewars.com/) to practice our developer skills. As a start, head into the algorithms section, and try this one: https://www.hackerrank.com/challenges/grading/problem.
- [ ] To turn this in, create a [gist](https://gist.github.com) of your code and submit link to it.

### Epic Mode

- [ ] Go back and finish up any outstanding work.
- [ ] Go back to a previous assignment and work on it some more. This could trying to tackle a harder level, working on the UI/UX, refactoring the code to a new idea that we covered (e.g. functions and abstractions), or adding unit tests.
- [ ] To turn this in, link to the other project's repository, and describe what you did.

**Comment by solismc** [comment]
https://medium.com/@manolocsolis/social-media-html-css-and-js-one-does-not-belong-or-does-it-4abc3b626799

**Comment by mdewey** [comment]
![Awesome Work!](https://media3.giphy.com/media/opvm3FXT2qYus/200w_d.gif)
